-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('student', 'teacher', 'hod', 'principal', 'admin')),
    department TEXT,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Student Details Table (Holds profile details)
CREATE TABLE IF NOT EXISTS student_details (
    id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    course TEXT NOT NULL,
    roll_number TEXT NOT NULL,
    prn_number TEXT NOT NULL UNIQUE,
    semester TEXT NOT NULL,
    division TEXT NOT NULL,
    parent_name TEXT,
    parent_phone TEXT,
    blood_group TEXT,
    aadhaar_number TEXT,
    category TEXT,
    emergency_contact TEXT,
    address TEXT,
    verified_documents TEXT[] DEFAULT '{}'::TEXT[],
    photo_url TEXT
);

-- 3. Create Notices / Announcements Table
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    category TEXT NOT NULL CHECK (category IN ('academics', 'placement', 'general')),
    publish_date DATE DEFAULT CURRENT_DATE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- 4. Create Attendance Table
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    subject TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent', 'Late')),
    marked_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- 5. Create Grades Table
CREATE TABLE IF NOT EXISTS grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    marks_obtained INTEGER NOT NULL,
    marks_total INTEGER NOT NULL,
    exam_name TEXT NOT NULL,
    entered_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- 6. Create Fees Installments Ledger Table
CREATE TABLE IF NOT EXISTS fees_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES users(id) ON DELETE CASCADE,
    installment_name TEXT NOT NULL,
    due_date DATE,
    amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Paid', 'Pending')),
    payment_date TIMESTAMP WITH TIME ZONE,
    receipt_url TEXT
);

-- 7. Create Assignments Table
CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT,
    given_date DATE DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    created_by UUID REFERENCES users(id) ON DELETE CASCADE
);

-- 8. Create Assignment Submissions Table
CREATE TABLE IF NOT EXISTS assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES assignments(id) ON DELETE CASCADE,
    student_id UUID REFERENCES users(id) ON DELETE CASCADE,
    submission_text TEXT,
    file_url TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT NOT NULL DEFAULT 'Submitted' CHECK (status IN ('Submitted', 'Graded', 'Late')),
    marks_obtained INTEGER,
    feedback TEXT,
    graded_by UUID REFERENCES users(id)
);

-- 9. Create Study Materials Table
CREATE TABLE IF NOT EXISTS study_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    title TEXT NOT NULL,
    file_url TEXT NOT NULL,
    publish_date DATE DEFAULT CURRENT_DATE,
    uploaded_by UUID REFERENCES users(id) ON DELETE CASCADE
);

-- 10. Create Website Master Content Settings Table
CREATE TABLE IF NOT EXISTS website_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed basic settings template
INSERT INTO website_settings (key, value) VALUES (
    'master_content',
    '{
      "girls_hostel": {
        "title": "Girls Hostels Limits",
        "details": ["Safe residential boarding inside secure campus perimeters for outstation students."],
        "rules": ["Located inside campus limits.", "24/7 security wardens present."]
      },
      "scholarships": {
        "title": "Welfare Scholarships Assistance",
        "details": ["Rajarshi Chhatrapati Shahu Maharaj concessions.", "Government Post-Matric schemes."]
      },
      "infrastructure": {
        "title": "Infrastructure assets",
        "details": ["Modern computing centers and smart classrooms guidelines."]
      }
    }'::jsonb
) ON CONFLICT (key) DO NOTHING;
